accounts/urls.py
from django.contrib.auth import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

hasanat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.main, name = 'main'),
	path('space/<int:space_id>/', views.SpaceDetail, name = 'space_detail_url'),
	path('task/<int:list_id>/', views.task, name = 'task_url'),
	# path('subtask/<int:task_id>/', views.subtask, name = 'subtask_url'),
	path('task_detail/<int:list_id>/<int:task_id>/', views.TaskDetail, name = 'task_detail_url'),

	path('status/<int:task_id>/', views.status, name = 'status_url')
] 

main/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from colorfield.fields import ColorField



class Status(models.Model):
    name_status = models.CharField(max_length=100)

    def __str__(self):
        return(self.name_status)

class Action(models.Model):
    name_action = models.CharField(max_length=100)

    def __str__(self):
        return(self.name_action)


class Space(models.Model):
    name = models.CharField('Название',max_length=100)
    photo = models.ImageField(upload_to='images/', blank=True)
    assign = models.ManyToManyField(User)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    add_date = models.DateField(auto_now_add=True)
    upd_date = models.DateField(auto_now_add=False, auto_now=True)
    created_by = models.CharField(max_length=150)
    color = ColorField(default='#FF0000')

    def __str__(self):
        return (self.name)



class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', blank=True, default='default_avatar/img_avatar2.png')
    email = models.EmailField()
    action = models.ForeignKey(Action, on_delete=models.CASCADE, default='')


    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ['user']
        verbose_name = 'user'
        verbose_name_plural = 'users'


class List(models.Model):
    space = models.ForeignKey(Space, on_delete=models.CASCADE, related_name='second')
    name_list = models.CharField(max_length=100)
    def __str__(self):
        return (self.name_list)


class Task(models.Model):
    lists = models.ForeignKey(List, on_delete=models.CASCADE, related_name='third')
    task_name = models.CharField(max_length=80, default='taskssssss', blank=True, null = True)
    assign = models.ManyToManyField(User, default=1, blank=True, null = True)
    dead_line = models.DateField()
    attachments = models.FileField(upload_to='files/',blank=True, null = True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE, default=2, blank=True, null = True)
    description = models.TextField(blank=True, null = True, default='descriptionssssssss')
    start_date = models.DateTimeField(auto_now_add=True, blank=True)
    end_date = models.DateTimeField()
    created_by = models.CharField(max_length=150, blank=True, null = True, default='admin')

    def __str__(self):
        return(self.task_name)

class SubTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='four')
    task_name = models.CharField(max_length=80)
    assign = models.ManyToManyField(User)
    dead_line = models.DateField()
    attachments = models.FileField(upload_to='files/',blank=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    start_date = models.DateTimeField(auto_now_add=True, blank=True)

    end_date = models.DateTimeField(blank=True, null = True)
    created_by = models.CharField(max_length=150, null = True)


    def __str__(self):
        return(self.task_name)

class TaskComment(models.Model):
    task = models.ForeignKey(Task,on_delete=models.CASCADE, related_name = 'task_comment')
    name = models.CharField(max_length=100)
    comment  = models.TextField(blank=True)

    def __str__(self):
        return(self.comment)

class SubTaskComment(models.Model):
    subtask = models.ForeignKey(SubTask,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment  = models.TextField(blank=True)

    def __str__(self):
        return(self.comment)

main/forms.py
from django.forms import ModelForm, DateInput, TextInput,HiddenInput,Textarea
from .models import *
from django.contrib.auth.models import User

class SpaceForm(ModelForm):
	class Meta:
		model = Space
		fields = ('name', 'photo', 'assign', 'status', 'created_by', 'color')
		widgets = {
			'color': TextInput(attrs={'type':'color'})
		}
		


class ListForm(ModelForm):
	class Meta:
		model = List
		fields = ('space','name_list',)

class TaskForm(ModelForm):
	class Meta:
		model = Task
		fields = ['lists','task_name', 'assign', 'dead_line', 'attachments', 'status', 'description', 'end_date', 'created_by']
		widgets = {
			'lists':HiddenInput(),
			'dead_line': DateInput(attrs={'type': 'date'}),
			'end_date': DateInput(attrs={'type': 'date'}),
		}
		

class SubTaskForm(ModelForm):
	class Meta:
		model = SubTask
		fields = ('task','task_name', 'assign', 'dead_line', 'attachments', 'status', 'description', 'end_date', 'created_by')

		widgets = {
			'task':HiddenInput(),
			'dead_line': DateInput(attrs={'type': 'date'}),
			'end_date': DateInput(attrs={'type': 'date'}),
		}

class TaskCommentForm(ModelForm):
	class Meta:
		model = TaskComment
		fields = ('task','name', 'comment')
		widgets = {
			'task': HiddenInput(),
			'comment': Textarea(attrs = {'class': 'form-control comment-area'})
		}

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from .forms import *
from django.views.generic import View
from django.urls import reverse
from django.http import HttpResponseRedirect

def main(request):
	space = Space.objects.filter(assign=request.user.id)
	if request.method == "POST":
		form_list = ListForm(request.POST)
		if form_list.is_valid():
			post = form_list.save()
			post.save()
			return redirect ('/')
	else:
		form_list = ListForm()

	if request.method == "POST":
		form_space = SpaceForm(request.POST)
		if form_space.is_valid():
			post = form_space.save()
			post.save()
			return redirect ('/')
	else:
		form_space = SpaceForm()
	return render(request, 'main/index.html', context = {'space':space, 'form_list': form_list, 'form_space': form_space})

def status(request, task_id):
	lists = List.objects.all()
	space = Space.objects.filter(assign=request.user.id)
	bbs = Task.objects.filter(status=task_id, assign=request.user.id)
	form_list = ListForm()
	form_space = SpaceForm()
	status = Status.objects.all()
	current_status = Status.objects.get(id = task_id)
	context = {
		'status': status,
		'bbs':bbs,
		'current_status':current_status,
		'space':space, 
		'lists': lists, 
		'form_list': form_list,
		'form_space': form_space,
	}
	return render(request, 'main/status.html', context)

def task(request, list_id):
	space = Space.objects.filter(assign=request.user.id)
	lists = get_object_or_404(List, id=list_id)
	form_list = ListForm()
	form_space = SpaceForm()
	status = Status.objects.all()

	if request.method == "POST":
		task_form = TaskForm(request.POST or None)
		if task_form.is_valid():
			task = task_form.save()
			task.save()
			return redirect(reverse('task_url', args = (lists.id,)))
	else:
		task_form = TaskForm(initial = {'lists': lists})
	return render(request, 'main/task.html', context = {'status':status,'lists':lists, 'space':space, 'form_list': form_list, 'form_space': form_space, 'task_form': task_form})

# def subtask(request, task_id):
# 	space = Space.objects.filter(assign=request.user.id)
# 	task = get_object_or_404(Task, id=task_id)
# 	form_list = ListForm()
# 	form_space = SpaceForm()

# 	if request.method == "POST":
# 		subtask_form = SubTaskForm(request.POST)
# 		if subtask_form.is_valid():
# 			post = subtask_form.save()
# 			post.save()
# 			return redirect(reverse('subtask_url', args = (task.id,)))
# 	else:
# 		subtask_form = SubTaskForm(initial = {'task': task})
# 	context = {
# 		'task':task,
# 		'subtask_form': subtask_form,
# 		'space':space, 
# 		'form_list': form_list, 
# 		'form_space': form_space,
# 		}
# 	return render(request, 'main/subtask.html', context = context)

def TaskDetail(request, task_id, list_id):
	task = get_object_or_404(Task, id=task_id)
	lists = get_object_or_404(List, id=list_id)
	form_upd = TaskForm(instance = task, initial = {'lists' : lists}) 
	latest_comments_list = task.task_comment.order_by('-id')[:10]
	task_comment_form = TaskCommentForm(request.POST)
	if task_comment_form.is_valid():
		task_comment_save = task_comment_form.save()
		return HttpResponseRedirect(reverse('task_detail_url', args = (lists.id,task.id)))
	forms = TaskForm(request.POST, instance = task)
	if forms.is_valid():
		upd_task = forms.save()
		return redirect(reverse('task_detail_url', args = (lists.id,task.id)))

	
	form_task_comment = TaskCommentForm(initial = {'task': task})

	if request.method == "POST":
		subtask_form = SubTaskForm(request.POST)
		if subtask_form.is_valid():
			post = subtask_form.save()
			post.save()
			return redirect(reverse('task_detail_url', args = (lists.id,task.id)))
	else:
		subtask_form = SubTaskForm(initial = {'task': task})
	if request.method == 'POST':
		task.delete()
		return redirect(reverse('task_url', args = (lists.id,)))
	context = {
	'form_task_comment': form_task_comment,
	"task_detail": task, 
	'form_upd': form_upd, 
	'lists': lists,  
	'latest_comments_list': latest_comments_list,
	'subtask_form': subtask_form,
	}
	return render(request, 'main/task_detail.html', context = context)

def SpaceDetail(request, space_id):
	space = get_object_or_404(Space, id=space_id)
	form_list = ListForm()
	form_space = SpaceForm()
	if request.method == 'POST':
		space.delete()
		return redirect(reverse('main'))
	return render(request, 'main/space_detail.html', context = {'space': space, 'form_list': form_list, 'form_space': form_space})

if __name__ == '__main__':
    	DEBAG = True

templates/main/create_space.html
{% extends 'base.html' %} 
{% block main %}
{% if user.is_authenticated %}
<span>{{ user.username }}</span>
<a href="{% url 'accounts:logout' %}" class="reg">Выйти</a>
    <form action="{%url 'create_space'%}" method='POST' id='form_create'>{%csrf_token%}
        <p>{{form.name}}</p>
        <p>{{form.photo}}</p>
        <p>{{form.assign}}</p>
        <p>{{form.status}} </p>
        <p><input type="text" name="created_by" maxlength="150" required="" id="id_created_by" hidden="" value="{{user.username}}"></p>
        <p><input type="color" id="id_color" class="form-control colorfield_field jscolor" name="color" value="#FF0000" placeholder="#FF0000" data-jscolor="{hash:true,width:225,height:150,required:true}" required=""></p>
        <p><input type="submit" name="submit" id="submit" value='submit'></p>
    </form> 
{% else %}
<a href="{% url 'accounts:login' %}" class="reg">Войти</a> 
{% endif %}

{% endblock%}

templates/main/index.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Main page{% endblock %} 
{% block content %} 

{% if user.is_authenticated %}

    

<div class="left">
<br> {% for i in space %}

<!--Accordion wrapper-->
<div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">

  <!-- Accordion card -->
  <div class="card">

    <!-- Card header 1-->
    <div class="card-header" role="tab" id="{{i.name}}">
      <a  data-toggle="collapse" data-parent="#accordionEx" href="#collapse{{i.name}}" aria-expanded="true"
        aria-controls="collapse{{i.name}}">
        <h5 class="mb-0" id="collapsediv">
          <div id="colorspace" style="background-color: {{i.color}}; "></div>{{i.name}}<i class="fas fa-angle-down rotate-icon"></i>
        </h5>
      </a>
    </div>

    <!-- Card body1 -->
    <div id="collapse{{i.name}}" class="collapse" role="tabpanel" aria-labelledby="{{i.name}}" data-parent="#accordionEx">
      <div class="card-body">
        {% for x in i.second.all %}
        <p><a href='{% url "task_url" x.id %}'>{{ x }}</a></p>
        {% endfor %}

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary mb-2" data-toggle="modal" data-target="#ListModal{{i.name}}">
 + Add List
</button>

<!-- Modal -->
<div class="modal fade" id="ListModal{{i.name}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalList" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalList">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       
            <form method='post' action="{%url 'main'%}">
                {%csrf_token%} {{form_list|crispy}}

            

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Add List</button>
        </form>
      </div>
    </div>
  </div>
</div>

        <a href="{% url 'space_detail_url' i.id %}" class="btn" style="background-color: {{i.color}}; color: white;">View detail {{i.name}}</a><br>
      </div>
    </div>

  </div>
  <!-- Accordion card -->
</div><br>
<!-- Accordion wrapper -->


    {% endfor %}

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#SpaceModal">
  + Add Space
</button>

<!-- Modal -->
<div class="modal fade" id="SpaceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalSpace" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalSpace">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{%url 'main'%}" method='POST' id='form_create'>{%csrf_token%}

      {{form_space.as_p}}
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Add Space</button>
        </form>
      </div>
    </div>
  </div>
</div>




</div>


    {% block main %} {% endblock %}

<!--
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Open modal for @getbootstrap</button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
    $('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('whatever') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text('New message to ' + recipient)
  modal.find('.modal-body input').val(recipient)
})
</script>
-->

{% else %}
    <a href="{% url 'accounts:login' %}" class="reg">Войти</a> 
{% endif %}

{% endblock %} 

templates/main/space_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}HELLO{% endblock %} 
{% block content %} 

	{{space.name}}
	<form method="post" action="{% url 'space_detail_url' space.id %}">
		{% csrf_token %}
		<button class="btn btn-danger">Delete</button>
	</form>
{% endblock %}

templates/main/subtask.html
{% extends 'main/index.html' %} {% load static %} {% load crispy_forms_tags %} {% block title %}SubTask{% endblock %} {% block main %} {% if user.is_authenticated %}





<div class="all">

    <div class="ri">
        <div class="name">
            <h6 class='textf'>Имя таска: </h6>
            <h6 class='textf'>Статус: </h6>
            <h6 class='textf'>Участники:</h6>

            <h6 class='textf'>Дедлайн: </h6>
            <h6 class='textf'>Начало:</h6>
            <h6 class='textf'>Завершено: </h6>
            <h6 class='textf'>Создано: </h6>
            <h6 class='textf'>Документ:</h6>
        </div>
        {% for xi in task.four.all %}
        <div class="borders">
            <div class="task">
                <h6>{{xi.task_name}}</h6>
            </div>
            <div class="status">
                <h6>{{xi.status}}</h6>
            </div>
            <div class="assign">
                {%for user in xi.assign.all%}
                <h6>{{user.username}}</h6>
                {%endfor%}</div>

            <div class="deadline">
                <h6>{{xi.dead_line}}</h6>
            </div>
            <div class="start">
                <h6>{{xi.start_date}}</h6>
            </div>
            <div class="end">
                <h6>{{xi.end_date}}</h6>
            </div>
            <div class="create">
                <h6>{{xi.created_by}}</h6>
            </div>
            <div class="file">
                <h6>{{xi.attachments}}</h6>
            </div>
        </div>
        {% endfor %}


        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary mb-2" data-toggle="modal" data-target="#SubTaskModal">
         + Add SubTask
        </button>

        <!-- Modal -->
        <div class="modal fade" id="SubTaskModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalList" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalList">Create SubTask</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{% url 'subtask_url' task.id %}">
                            {% csrf_token %} {{subtask_form|crispy}}

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Add SubTask</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

{% else %}
<a href="{% url 'accounts:login' %}" class="reg">Войти</a> {% endif %} {%endblock%}

templates/main/task_detail.html
{% load static %} 

{% load crispy_forms_tags %}{% block main %} {% if user.is_authenticated %}
<!doctype  html>
<html lang="en">

<head>
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Xanh+Mono:ital@1&display=swap" rel="stylesheet">
    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/task_detail.css' %}">
    <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <script type="text/javascript" src="{% static 'main/js/script.js' %}"></script>
    <title>Django Authentication Example</title>
</head>



<div class="header">
    <div class="back-d">
        <a href="/" class='back'> +</a>
    </div>
</div>
<div class="all">
<div class="left">
    <div class="under-t">
        <div class="status">
            <h6 class="status">{{task_detail.status}}</h6>
        </div>

        <div class="assign">

        
            {%for user in task_detail.assign.all%}
   {{user.username}}
            <img src="{% static 'main/default_avatar/img_avatar.png' %}" class='avatar'/>
                
            {%endfor%}
        </div>
        <div>
        <div class="create_by">
                    <h6 class="create_by">Create by: </h6>
                </div>
        <div class="create">
            <h6 class="create">{{task_detail.created_by}}</h6>
        </div>
</div>
        
    </div>

    <div class="task">
        <h6 class="task">{{task_detail.task_name}}</h6>
    </div>
    <div class="description">
        <h6 class="description">{{task_detail.description}}</h6>
    </div>
</div>    

<div class="right">
        <div class="borders">

            <div>
                <div class="created">
                    <h6 class="created">Created</h6>
                </div>
                <div class="start">
                    <h6 class="start">{{task_detail.start_date}}</h6>
                </div>
            </div>

            <div>
                <div class="dead">
                    <h6 class="dead">Deadline</h6>
                </div>
                <div class="deadline">
                    <h6 class="deadline">{{task_detail.dead_line}}</h6>
                </div>
            </div>

            <div>
                <div class="ends">
                    <h6 class="ends">End date</h6>
                </div>
                <div class="end">
                    <h6 class="end">{{task_detail.end_date}}</h6>
                </div>
            </div>
        </div>

            
            <div class="file">
                <h6>{{task_detail.attachments}}</h6>
            </div>
        


        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary mb-2" data-toggle="modal" data-target="#UpdateTaskModal">
 + Update Task
</button>

        <!-- Modal -->
        <div class="modal fade" id="UpdateTaskModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalList" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalList">Update Task</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{% url 'task_detail_url' lists.id task_detail.id %}">
                            {% csrf_token %} {{form_upd|crispy}}

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Update Task</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <form method="post" action="{% url 'task_detail_url' lists.id task_detail.id  %}">
            {% csrf_token %}
            <button class="btn btn-danger">Delete</button>
        </form>




        {% if latest_comments_list %} {% for c in latest_comments_list %}
        <p>
            <hr>
            <div class=""><span class="badge badge-success">{{c.name}}</span></div>
            <div class="">
                <p>{{c.comment}}</p>
            </div>

        </p>
        {% endfor %} {% else %}
        <div class="ml-3">Комментарии</div>
        {% endif %}



        <form method="post" action="{% url 'task_detail_url' lists.id task_detail.id %}">
            {% csrf_token %} 
            <input type="text" name="name" id="id_name" value="{{user.username}}">
            
            {{form_task_comment.comment}}
            <button class="btn btn-primary">Add Comment</button>
        </form>




            
            {% for xi in task_detail.four.all %}
            <div class="borders">
                <div class="task">
                    <h6>{{xi.task_name}}</h6>
                </div>
                <div class="status">
                    <h6>{{xi.status}}</h6>
                </div>
                <div class="assign">
                    {%for user in xi.assign.all%}
                    <h6>{{user.username}}</h6>
                    {%endfor%}</div>

                <div class="deadline">
                    <h6>{{xi.dead_line}}</h6>
                </div>
                <div class="start">
                    <h6>{{xi.start_date}}</h6>
                </div>
                <div class="end">
                    <h6>{{xi.end_date}}</h6>
                </div>
                <div class="create">
                    <h6>{{xi.created_by}}</h6>
                </div>
                <div class="file">
                    <h6>{{xi.attachments}}</h6>
                </div>
            </div>
            {% endfor %}


            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary mb-2" data-toggle="modal" data-target="#SubTaskModal">
           + Add SubTask
          </button>

            <!-- Modal -->
            <div class="modal fade" id="SubTaskModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalList" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalList">Create SubTask</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                        </div>
                        <div class="modal-body">
                            <form method="post" action="{% url 'task_detail_url' lists.id task_detail.id %}">
                                {% csrf_token %} {{subtask_form|crispy}}

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Add SubTask</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


</div>
</div>
        {% else %}

        <a href="{% url 'accounts:login' %}" class="reg">Войти</a> {% endif %} {%endblock%}